Feature/comparer
juanjosegb/reactamorty-project pull request #1
Opened 2020-03-24 07:55 UTC by juanjosegb

2020-03-24 10:53 UTC, alexhoo commented on src/store/sagas/characters/index.tsx
> +        results = yield (GetAllCharactersByPage(action.payload).then(
El uso de yield es parecido al uso de async await, no tienes que poner "then" a la llamada a una función
en este caso sería:
```
const results: ICharacter[] = yield call(GetAllCharactersByPage, action.payload)
y en results ya tendrías los resultados

2020-03-24 10:53 UTC, alexhoo commented on src/store/sagas/characters/index.tsx
> +        results = yield (GetAllCharacters().then(
lo mismo que antes

2020-03-24 10:56 UTC, alexhoo commented on src/screens/ComparerScreen/index.tsx
> +                                        {firstCharacter && firstCharacter.status}
Así mejor: 
```
{ firstCharacter ? firstCharacter.status : defaultSlash }
```

2020-03-24 10:57 UTC, alexhoo commented on src/components/Common/ComparerInput/index.tsx
> +                    renderOption={(option, {selected}) => (
esto es mejor sacarlo a una función fuera

2020-03-24 10:59 UTC, alexhoo commented on src/components/Common/ComparerInput/index.tsx
> +    }, []);
¿dónde controlas qué ocurre a la interfaz mientras se está haciendo el fetch? que pasa si toma 5 segundos? como se refleja eso en la vista?

2020-03-24 11:00 UTC, alexhoo requested changes
Echale un vistazo a los comentarios

2020-03-25 09:47 UTC, juanjosegb commented on src/components/Common/ComparerInput/index.tsx
> +    }, []);
Al parecer el mismo autocomplete tiene un atributo loading que junto con el isFetching de la saga funciona bien. Ahora si el listado esta cargando sale un Loading.

2020-03-25 09:47 UTC, juanjosegb commented on src/components/Common/ComparerInput/index.tsx
> +                    renderOption={(option, {selected}) => (
Ya he sacado ambas funciones fuera como una función flecha.

2020-03-25 09:48 UTC, juanjosegb commented on src/screens/ComparerScreen/index.tsx
> +                                        {firstCharacter && firstCharacter.status}
Perfecto, me ahorro un montón de lineas con esto.

2020-03-25 09:57 UTC, juanjosegb commented on src/store/sagas/characters/index.tsx
> +        results = yield (GetAllCharactersByPage(action.payload).then(
Este ha sido un poco lo que mas he tenido que darle vueltas porque al ponerlo me fallaba la saga y no sabia de donde venia, pero bueno te explico:

He tenido que modificar lo que me decías en dos de las sagas porque lo que devuelve GetAllCharactersByPage no son ICharacter[] sino una Promise, entonces he tenido que ponerle directamente un response: any y de ahi sacar los characters y el total de paginas que para ello he creado una interfaz.

De todos modos desconocia por completo la función call esta que me simplifica bastante todo, hasta ahora usaba el then en la saga para todo.

Igualmente si ves otra forma de hacer lo del response me lo comentas porque ya te digo no sabia de que forma sacar atributos del response directamente sin obtener antes el response en una variable.

2020-03-27 07:55 UTC, alexhoo approved these changes
Esta vez mejor, échale un ojo a eso que te he puesto

2020-03-27 07:55 UTC, alexhoo commented on src/components/Common/ComparerInput/index.tsx
> +                    loading={getCharactersFetching(charactersState)}
Normalmente, antes del return, se suele desestructurar o recuperar la parte del store que vas a usar para controlar partes de la vista, en este caso por ejemplo, el isFetching, los items, etc.
```
const isFetching = getCharactersFetching(charactersState)
...
// mas tarde
return {
return (
        <CenterContainer>
            <InlinePaperFilter component="form">
}
```

2020-03-27 07:55 UTC, alexhoo commented on src/components/Common/ComparerInput/index.tsx
> +                    onChange={handleChange()}
no creo que esto te esté funcionando ya que o:
```
onChange={handleChange}   // implicitamente estaría recibiendo el event
```
o
```
onChange={(ev) => handleChange(ev)}
```

2020-03-27 10:35 UTC, juanjosegb commented on src/components/Common/ComparerInput/index.tsx
> +                    onChange={handleChange()}
Pues si te digo la verdad funcionaba pero yo tampoco sabía porque, directamente hice refactor con el webstorm y me lo puso de esa forma. Pero vamos que tienes razón esta mejor de esa forma, ya esta cambiado.

2020-03-27 10:36 UTC, juanjosegb commented on src/components/Common/ComparerInput/index.tsx
> +                    loading={getCharactersFetching(charactersState)}
Pues mira que destructuro props y demás pero no se me había ocurrido también hacerlo con los fetch.

2020-03-27 12:27 UTC, merged